
package paresimpares;

/**
 * Esta clase amosa unha xanela con dous borons e unha combo box, que se enchera
 *  numeros pares ou impares(dependendo do boton pulsado) entre 0 e 100
 * 
 * @author Xaquin Alves Gonzalez
 */
public class ParesImpares extends javax.swing.JFrame {

    /**
     * Creates new form ParesImpares
     */
    public ParesImpares() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonEven = new javax.swing.JButton();
        jButtonOdd = new javax.swing.JButton();
        jComboBoxNumbers = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonEven.setText("Pares");
        jButtonEven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEvenActionPerformed(evt);
            }
        });

        jButtonOdd.setText("Impares");
        jButtonOdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButtonEven, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jButtonOdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jComboBoxNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jComboBoxNumbers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOdd)
                    .addComponent(jButtonEven))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    /**
     * Chama a emptyNumbers() e despois a fillEven()
     *
     * @param evt
     */
    private void jButtonEvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEvenActionPerformed
        emptyNumbers();
        fillEven();
    }//GEN-LAST:event_jButtonEvenActionPerformed
    /**
     *  Chama a emptyNumbers() e despois a  fillOdd()
     *
     * @param evt
     */
    private void jButtonOddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOddActionPerformed
        emptyNumbers();
        fillOdd();
    }//GEN-LAST:event_jButtonOddActionPerformed
    
    /**
     * Vacia a ComboBox
     */
    private void emptyNumbers() {
        jComboBoxNumbers.removeAllItems();
    }

    /**
     * Enche o ComboBox cos numeros pares entre 0 e 100
     */
    private void fillEven() {
        for (int i = 2; i < 100; i += 2) {
            jComboBoxNumbers.addItem(String.valueOf(i));
        }
    }

    /**
     * Enche o ComboBox cos numeros impares entre 0 e 100
     */
    private void fillOdd() {
        for (int i = 1; i < 100; i += 2) {
            jComboBoxNumbers.addItem(String.valueOf(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParesImpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParesImpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParesImpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParesImpares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParesImpares().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEven;
    private javax.swing.JButton jButtonOdd;
    private javax.swing.JComboBox<String> jComboBoxNumbers;
    // End of variables declaration//GEN-END:variables
}
