package animales2;

import javax.swing.JOptionPane;

/**
 * Esta clase crea unha xanela con 3 opcions(can, gato, galo) e un boton que o
 * pulsalo crea un diálogo co son que fan os animais seleccionados
 *
 * @author Xaquin Alves Gonzalez
 */
public class AnimalesGUI2 extends javax.swing.JFrame {

    /**
     * Creates new form AnimalesGUI
     */
    public AnimalesGUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMensaxe = new javax.swing.JDialog();
        jButtonFalar = new javax.swing.JButton();
        jCheckCan = new javax.swing.JCheckBox();
        jCheckGato = new javax.swing.JCheckBox();
        jCheckGalo = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialogMensaxeLayout = new javax.swing.GroupLayout(jDialogMensaxe.getContentPane());
        jDialogMensaxe.getContentPane().setLayout(jDialogMensaxeLayout);
        jDialogMensaxeLayout.setHorizontalGroup(
            jDialogMensaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogMensaxeLayout.setVerticalGroup(
            jDialogMensaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFalar.setText("Falar");
        jButtonFalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFalarActionPerformed(evt);
            }
        });

        jCheckCan.setText("Can");

        jCheckGato.setText("Gato");

        jCheckGalo.setText("Galo");
        jCheckGalo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckGaloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonFalar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckGato)
                            .addComponent(jCheckCan)
                            .addComponent(jCheckGalo))))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jCheckCan)
                .addGap(20, 20, 20)
                .addComponent(jCheckGato)
                .addGap(20, 20, 20)
                .addComponent(jCheckGalo)
                .addGap(60, 60, 60)
                .addComponent(jButtonFalar)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** 
     * Abre un dialogo cunha mensaxe dependendo das opcions seleccionadas
     * @param evt
     */
    
    private void jButtonFalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFalarActionPerformed
        String mensage = "";
        if (jCheckCan.isSelected()) {
            mensage += "GUAU! ";
        } 
        if (jCheckGato.isSelected()) {
            mensage += "miau ";
        }
        if (jCheckGalo.isSelected()) {
            mensage += "KIKIRIKII!!!! ";
        }

        JOptionPane.showMessageDialog(jDialogMensaxe, mensage);
    }//GEN-LAST:event_jButtonFalarActionPerformed

    private void jCheckGaloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckGaloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckGaloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalesGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFalar;
    private javax.swing.JCheckBox jCheckCan;
    private javax.swing.JCheckBox jCheckGalo;
    private javax.swing.JCheckBox jCheckGato;
    private javax.swing.JDialog jDialogMensaxe;
    // End of variables declaration//GEN-END:variables
}
