package animales3;

import javax.swing.JOptionPane;

/**
 * Esta clase crea unha xanela con 3 opcions(can, gato, galo) e un boton que o
 * pulsalo crea un diálogo co son que fai o animal seleccionado, e se se escribe
 * un distinto da erro
 *
 * @author Xaquin Alves Gonzalez
 */
public class AnimalesGUI3 extends javax.swing.JFrame {

    /**
     * Creates new form AnimalesGUI
     */
    public AnimalesGUI3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogMensaxe = new javax.swing.JDialog();
        jButtonFalar = new javax.swing.JButton();
        jComboBoxAnimal = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jDialogMensaxeLayout = new javax.swing.GroupLayout(jDialogMensaxe.getContentPane());
        jDialogMensaxe.getContentPane().setLayout(jDialogMensaxeLayout);
        jDialogMensaxeLayout.setHorizontalGroup(
            jDialogMensaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogMensaxeLayout.setVerticalGroup(
            jDialogMensaxeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonFalar.setText("Falar");
        jButtonFalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFalarActionPerformed(evt);
            }
        });

        jComboBoxAnimal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Can", "Gato", "Galo" }));
        jComboBoxAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFalar))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jComboBoxAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButtonFalar)
                .addGap(45, 45, 45))
        );

        jComboBoxAnimal.setEditable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /** 
     * Abre un dialogo cunha mensaxe dependendo da opcion seleccionada nun cadro
     * desplegable. Podese editar, pero se se pon un animal distinto da erro
     * @param evt
     */
    
    private void jButtonFalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFalarActionPerformed
        String mensage = "";
        if(jComboBoxAnimal.getSelectedItem().toString().equals("Can")){
            mensage = "GUAU!";
        }else if(jComboBoxAnimal.getSelectedItem().toString().equals("Gato")){
            mensage = "miau";
        }else if(jComboBoxAnimal.getSelectedItem().toString().equals("Galo")){
            mensage = "KIKIRIKI!!!";
        }else{
            mensage = "Erro: Animal descoñecido";
        }

        JOptionPane.showMessageDialog(jDialogMensaxe, mensage);
    }//GEN-LAST:event_jButtonFalarActionPerformed

    private void jComboBoxAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAnimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimalesGUI3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimalesGUI3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFalar;
    private javax.swing.JComboBox<String> jComboBoxAnimal;
    private javax.swing.JDialog jDialogMensaxe;
    // End of variables declaration//GEN-END:variables
}
