package padelmanager.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import padelmanager.model.Booking;
import padelmanager.model.DoubleBooking;

/**
 * Este dialogo permite escoller entre unha lista de reservas amosadas
 * 
 * @author Xaquin Alves González
 */
public class SelectBookingJDialog extends javax.swing.JDialog {

    /**
     * Para saber se o usuario acoptou a acción ou non
     */
    private boolean actionAccepted;
    /**
     * Equipo selecionado polo usuario
     */
    private int selectedTeam;
    /**
     * Lista de reservas que se amosa ao usuario
     */
    private ArrayList<Booking> bookings;

    /**
     *
     * @return true se o cadro de dialago pechouse por pulsar aceptar, se foi
     * por pulsar cancelar false
     */
    public boolean isActionAccepted() {
        return actionAccepted;
    }

    /**
     *
     * @return o numero do equipo escollido
     */
    public int getSelectedTeam() {
        return selectedTeam;
    }

    /**
     *
     * @return a lista das reservas do dia escollido as que se pode unir o
     * xogador
     */
    public ArrayList<Booking> getBookings() {
        return bookings;
    }

    /**
     * Establece unha nova lista das reservas do dia escollido as que se pode
     * unir o xogador
     *
     * @param bookings lista das reservas do dia escollido as que se pode unir o
     * xogador
     */
    public void setBookings(ArrayList<Booking> bookings) {
        this.bookings = bookings;

        DefaultListModel listModel = new DefaultListModel();
        jListBookings.setModel(listModel);
        for (Booking bk : this.bookings) {
            listModel.addElement(bk.getDescription());
        }
    }

    /**
     *
     * @return a reserva seleccionada polo usuario
     */
    public Booking getSelectedBooking() {
        return bookings.get(jListBookings.getSelectedIndex());
    }

    /**
     * Creates new form SelectBookingJDialog
     */
    public SelectBookingJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelControls = new javax.swing.JPanel();
        jButtonAcept = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPaneBookings = new javax.swing.JScrollPane();
        jListBookings = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 200));
        setPreferredSize(new java.awt.Dimension(540, 240));

        jPanelTitle.setBackground(new java.awt.Color(204, 204, 204));
        jPanelTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabelTitle.setForeground(new java.awt.Color(0, 0, 0));
        jLabelTitle.setText("Selecciona o partido ao que te queres unir:");
        jPanelTitle.add(jLabelTitle);

        getContentPane().add(jPanelTitle, java.awt.BorderLayout.PAGE_START);

        jPanelControls.setBackground(new java.awt.Color(204, 204, 204));
        jPanelControls.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonAcept.setText("Aceptar");
        jButtonAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptActionPerformed(evt);
            }
        });
        jPanelControls.add(jButtonAcept);

        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelControls.add(jButtonCancel);

        getContentPane().add(jPanelControls, java.awt.BorderLayout.PAGE_END);

        jScrollPaneBookings.setBackground(new java.awt.Color(204, 204, 204));

        jListBookings.setBackground(new java.awt.Color(255, 255, 255));
        jListBookings.setForeground(new java.awt.Color(0, 0, 0));
        jListBookings.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPaneBookings.setViewportView(jListBookings);

        getContentPane().add(jScrollPaneBookings, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Accion realizada ao pulsar o boton Aceptar
     *
     * @param evt
     */
    private void jButtonAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptActionPerformed
        if (jListBookings.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar unha reserva");
        } else {
            if (bookings.get(jListBookings.getSelectedIndex()) instanceof DoubleBooking) {
                selectedTeam = Integer.parseInt(JOptionPane.showInputDialog(this, "Indica o equipo ao que te queres apuntar(1/2)")) - 1;
            }
            actionAccepted = true;
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAceptActionPerformed
    /**
     * Accion realizada ao pulsar o boton Cancelar
     *
     * @param evt
     */
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        actionAccepted = false;
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectBookingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectBookingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectBookingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectBookingJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            SelectBookingJDialog dialog = new SelectBookingJDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListBookings;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPaneBookings;
    // End of variables declaration//GEN-END:variables
}
