package ui;

import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import memorygame.ArrayCardGenerator;
import memorygame.Card;
import memorygame.GenerateCardsException;

/**
 *
 * @author Xaquin Alves
 */
public class MemoryGame extends javax.swing.JFrame {

    private Card[][] cards;
    private JToggleButton[][] toggleButtons;
    private Card lastSelectedCard;
    private JToggleButton lastSelectedButton;
    private int points;

    /**
     * Creates new form MemoryGame
     */
    public MemoryGame() {
        initComponents();
        toggleButtons = new JToggleButton[3][4];
        toggleButtons[0][0] = button11;
        toggleButtons[0][1] = button12;
        toggleButtons[0][2] = button13;
        toggleButtons[0][3] = button14;
        toggleButtons[1][0] = button21;
        toggleButtons[1][1] = button22;
        toggleButtons[1][2] = button23;
        toggleButtons[1][3] = button24;
        toggleButtons[2][0] = button31;
        toggleButtons[2][1] = button32;
        toggleButtons[2][2] = button33;
        toggleButtons[2][3] = button34;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING:
     * Do NOT modify this code. The content of this method is always regenerated by the
     * Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEstado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelNivel = new javax.swing.JLabel();
        jComboBoxNivel = new javax.swing.JComboBox<>();
        jButtonNovaPartida = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jPanelCentral = new javax.swing.JPanel();
        button11 = new javax.swing.JToggleButton();
        button12 = new javax.swing.JToggleButton();
        button13 = new javax.swing.JToggleButton();
        button14 = new javax.swing.JToggleButton();
        button21 = new javax.swing.JToggleButton();
        button22 = new javax.swing.JToggleButton();
        button23 = new javax.swing.JToggleButton();
        button24 = new javax.swing.JToggleButton();
        button31 = new javax.swing.JToggleButton();
        button32 = new javax.swing.JToggleButton();
        button33 = new javax.swing.JToggleButton();
        button34 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelEstado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelEstado.setForeground(new java.awt.Color(0, 0, 0));
        jLabelEstado.setText("Nivel de xogo: Puntuacion:");
        jPanel1.add(jLabelEstado);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabelNivel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNivel.setForeground(new java.awt.Color(0, 0, 0));
        jLabelNivel.setText("Nivel:");
        jPanel3.add(jLabelNivel);

        jComboBoxNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinxelo", "Medio", "Dificil" }));
        jPanel3.add(jComboBoxNivel);

        jButtonNovaPartida.setText("Nova partida");
        jButtonNovaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovaPartidaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonNovaPartida);

        jButtonSair.setText("Saír");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSair);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanelCentral.setBackground(new java.awt.Color(153, 153, 153));
        jPanelCentral.setLayout(new java.awt.GridLayout(3, 4));

        button11.setEnabled(false);
        button11.setMaximumSize(new java.awt.Dimension(200, 200));
        button11.setMinimumSize(new java.awt.Dimension(100, 100));
        button11.setPreferredSize(new java.awt.Dimension(200, 200));
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button11);

        button12.setEnabled(false);
        button12.setMaximumSize(new java.awt.Dimension(200, 200));
        button12.setMinimumSize(new java.awt.Dimension(100, 100));
        button12.setPreferredSize(new java.awt.Dimension(200, 200));
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button12);

        button13.setEnabled(false);
        button13.setMaximumSize(new java.awt.Dimension(200, 200));
        button13.setMinimumSize(new java.awt.Dimension(100, 100));
        button13.setPreferredSize(new java.awt.Dimension(200, 200));
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button13);

        button14.setEnabled(false);
        button14.setMaximumSize(new java.awt.Dimension(200, 200));
        button14.setMinimumSize(new java.awt.Dimension(100, 100));
        button14.setPreferredSize(new java.awt.Dimension(200, 200));
        button14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button14ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button14);

        button21.setEnabled(false);
        button21.setMaximumSize(new java.awt.Dimension(200, 200));
        button21.setMinimumSize(new java.awt.Dimension(100, 100));
        button21.setPreferredSize(new java.awt.Dimension(200, 200));
        button21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button21ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button21);

        button22.setEnabled(false);
        button22.setMaximumSize(new java.awt.Dimension(200, 200));
        button22.setMinimumSize(new java.awt.Dimension(100, 100));
        button22.setPreferredSize(new java.awt.Dimension(200, 200));
        button22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button22ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button22);

        button23.setEnabled(false);
        button23.setMaximumSize(new java.awt.Dimension(200, 200));
        button23.setMinimumSize(new java.awt.Dimension(100, 100));
        button23.setPreferredSize(new java.awt.Dimension(200, 200));
        button23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button23ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button23);

        button24.setEnabled(false);
        button24.setMaximumSize(new java.awt.Dimension(200, 200));
        button24.setMinimumSize(new java.awt.Dimension(100, 100));
        button24.setPreferredSize(new java.awt.Dimension(200, 200));
        button24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button24ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button24);

        button31.setEnabled(false);
        button31.setMaximumSize(new java.awt.Dimension(200, 200));
        button31.setMinimumSize(new java.awt.Dimension(100, 100));
        button31.setPreferredSize(new java.awt.Dimension(200, 200));
        button31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button31ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button31);

        button32.setEnabled(false);
        button32.setMaximumSize(new java.awt.Dimension(200, 200));
        button32.setMinimumSize(new java.awt.Dimension(100, 100));
        button32.setPreferredSize(new java.awt.Dimension(200, 200));
        button32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button32ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button32);

        button33.setEnabled(false);
        button33.setMaximumSize(new java.awt.Dimension(200, 200));
        button33.setMinimumSize(new java.awt.Dimension(100, 100));
        button33.setPreferredSize(new java.awt.Dimension(200, 200));
        button33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button33ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button33);

        button34.setEnabled(false);
        button34.setMaximumSize(new java.awt.Dimension(200, 200));
        button34.setMinimumSize(new java.awt.Dimension(100, 100));
        button34.setPreferredSize(new java.awt.Dimension(200, 200));
        button34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button34ActionPerformed(evt);
            }
        });
        jPanelCentral.add(button34);

        getContentPane().add(jPanelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ao usar o boton sair
     *
     * @param evt
     */
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Esta seguro de sair do xogo?", "Sair",
                                          JOptionPane.YES_NO_OPTION) ==
                JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButtonSairActionPerformed
    /**
     * Ao usar o boton nova partida
     *
     * @param evt
     */
    private void jButtonNovaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovaPartidaActionPerformed
        startNewGame(jComboBoxNivel.getSelectedIndex());
    }//GEN-LAST:event_jButtonNovaPartidaActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        uncover(0, 0);
    }//GEN-LAST:event_button11ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        uncover(0, 1);
    }//GEN-LAST:event_button12ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        uncover(0, 2);
    }//GEN-LAST:event_button13ActionPerformed

    private void button14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button14ActionPerformed
        uncover(0, 3);
    }//GEN-LAST:event_button14ActionPerformed

    private void button21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button21ActionPerformed
        uncover(1, 0);
    }//GEN-LAST:event_button21ActionPerformed

    private void button22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button22ActionPerformed
        uncover(1, 1);
    }//GEN-LAST:event_button22ActionPerformed

    private void button23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button23ActionPerformed
        uncover(1, 2);
    }//GEN-LAST:event_button23ActionPerformed

    private void button24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button24ActionPerformed
        uncover(1, 3);
    }//GEN-LAST:event_button24ActionPerformed

    private void button31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button31ActionPerformed
        uncover(2, 0);
    }//GEN-LAST:event_button31ActionPerformed

    private void button32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button32ActionPerformed
        uncover(2, 1);
    }//GEN-LAST:event_button32ActionPerformed

    private void button33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button33ActionPerformed
        uncover(2, 2);
    }//GEN-LAST:event_button33ActionPerformed

    private void button34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button34ActionPerformed
        uncover(2, 3);
    }//GEN-LAST:event_button34ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.
                    getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoryGame.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MemoryGame().setVisible(true);
        });
    }

    private void startNewGame(int nivel) {
        ArrayCardGenerator cardGenerator = new ArrayCardGenerator();

        try {
            cards = cardGenerator.generateCards(nivel + 2, 4);

            for (int i = 0; i < toggleButtons.length; i++) {
                for (int j = 0; j < toggleButtons[i].length; j++) {
                    toggleButtons[i][j].setEnabled(true);
                    toggleButtons[i][j].setSelected(false);
                    toggleButtons[i][j].setText("");

                    if (nivel == 0 && i == 2) {
                        toggleButtons[i][j].setEnabled(false);
                    }
                }
            }

            lastSelectedCard = null;
            points = 100;
            showGameStatus();
        }
        catch (GenerateCardsException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Erro",
                                          JOptionPane.ERROR_MESSAGE);
            for (int i = 0; i < toggleButtons.length; i++) {
                for (int j = 0; j < toggleButtons[i].length; j++) {
                    toggleButtons[i][j].setEnabled(false);
                }
            }
        }
    }

    private void showGameStatus() {
        jLabelEstado.setText("Nivel de xogo: " + jComboBoxNivel.getSelectedItem() +
                " Puntiacion: " + points);
    }

    private void clearUnselectedButtons() {
        for (int i = 0; i < toggleButtons.length; i++) {
            for (int j = 0; j < toggleButtons[i].length; j++) {
                if (toggleButtons[i][j].isEnabled() && !toggleButtons[i][j].isSelected()) {
                    toggleButtons[i][j].setText("");
                }
            }
        }
    }

    private void checkGameOver() {
        boolean keepGoing = true;

        for (int i = 0; i < cards.length && keepGoing; i++) {
            for (int j = 0; j < cards[i].length && keepGoing; j++) {
                keepGoing = cards[i][j].isHit();
            }
        }
        if (keepGoing) {
            JOptionPane.showMessageDialog(this, "Noraboa! Acertaches todas as" +
                                          "cartas, conseguindo " + points + " puntos!");
        }
    }

    private void uncover(int row, int col) {
        clearUnselectedButtons();
        toggleButtons[row][col].setText(cards[row][col].getText());

        if (lastSelectedCard == null) {
            lastSelectedCard = cards[row][col];
            lastSelectedButton = toggleButtons[row][col];
            toggleButtons[row][col].setEnabled(false);
        }
        else {
            if (lastSelectedCard.isEquals(cards[row][col])) {
                toggleButtons[row][col].setEnabled(false);
                lastSelectedCard.setHit(true);
                cards[row][col].setHit(true);
                checkGameOver();
            }
            else {
                lastSelectedButton.setSelected(false);
                toggleButtons[row][col].setSelected(false);
                lastSelectedButton.setEnabled(true);
                points -= 1;
                showGameStatus();
            }
            lastSelectedCard = null;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton button11;
    private javax.swing.JToggleButton button12;
    private javax.swing.JToggleButton button13;
    private javax.swing.JToggleButton button14;
    private javax.swing.JToggleButton button21;
    private javax.swing.JToggleButton button22;
    private javax.swing.JToggleButton button23;
    private javax.swing.JToggleButton button24;
    private javax.swing.JToggleButton button31;
    private javax.swing.JToggleButton button32;
    private javax.swing.JToggleButton button33;
    private javax.swing.JToggleButton button34;
    private javax.swing.JButton jButtonNovaPartida;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxNivel;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNivel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelCentral;
    // End of variables declaration//GEN-END:variables
}
